/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSuppliersImport } from './routes/_layout/suppliers'
import { Route as LayoutStoresImport } from './routes/_layout/stores'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutSalesImport } from './routes/_layout/sales'
import { Route as LayoutPurchasesImport } from './routes/_layout/purchases'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutItemunitsImport } from './routes/_layout/item_units'
import { Route as LayoutItemcategoriesImport } from './routes/_layout/item_categories'
import { Route as LayoutCustomersImport } from './routes/_layout/customers'
import { Route as LayoutCustomertypesImport } from './routes/_layout/customer_types'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutAccountsImport } from './routes/_layout/accounts'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSuppliersRoute = LayoutSuppliersImport.update({
  path: '/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoresRoute = LayoutStoresImport.update({
  path: '/stores',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesRoute = LayoutSalesImport.update({
  path: '/sales',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPurchasesRoute = LayoutPurchasesImport.update({
  path: '/purchases',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemunitsRoute = LayoutItemunitsImport.update({
  path: '/item_units',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemcategoriesRoute = LayoutItemcategoriesImport.update({
  path: '/item_categories',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCustomersRoute = LayoutCustomersImport.update({
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCustomertypesRoute = LayoutCustomertypesImport.update({
  path: '/customer_types',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAccountsRoute = LayoutAccountsImport.update({
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/accounts': {
      preLoaderRoute: typeof LayoutAccountsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/customer_types': {
      preLoaderRoute: typeof LayoutCustomertypesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/customers': {
      preLoaderRoute: typeof LayoutCustomersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/item_categories': {
      preLoaderRoute: typeof LayoutItemcategoriesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/item_units': {
      preLoaderRoute: typeof LayoutItemunitsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/purchases': {
      preLoaderRoute: typeof LayoutPurchasesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales': {
      preLoaderRoute: typeof LayoutSalesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/stores': {
      preLoaderRoute: typeof LayoutStoresImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/suppliers': {
      preLoaderRoute: typeof LayoutSuppliersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAccountsRoute,
    LayoutAdminRoute,
    LayoutCustomertypesRoute,
    LayoutCustomersRoute,
    LayoutItemcategoriesRoute,
    LayoutItemunitsRoute,
    LayoutItemsRoute,
    LayoutPurchasesRoute,
    LayoutSalesRoute,
    LayoutSettingsRoute,
    LayoutStoresRoute,
    LayoutSuppliersRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
